// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $datasets_dataset_ from "./routes/datasets/[dataset].tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $search_image from "./routes/search/image.tsx";
import * as $search_model from "./routes/search/model.tsx";
import * as $dropdown_model_select from "./islands/dropdown-model-select.tsx";
import * as $dropdown_model_version from "./islands/dropdown-model-version.tsx";
import * as $image_overlay from "./islands/image-overlay.tsx";
import * as $model_card from "./islands/model-card.tsx";
import * as $model_info from "./islands/model-info.tsx";
import * as $overflow_modal from "./islands/overflow-modal.tsx";
import * as $suggested_searchbar from "./islands/suggested-searchbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/datasets/[dataset].tsx": $datasets_dataset_,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/search/image.tsx": $search_image,
    "./routes/search/model.tsx": $search_model,
  },
  islands: {
    "./islands/dropdown-model-select.tsx": $dropdown_model_select,
    "./islands/dropdown-model-version.tsx": $dropdown_model_version,
    "./islands/image-overlay.tsx": $image_overlay,
    "./islands/model-card.tsx": $model_card,
    "./islands/model-info.tsx": $model_info,
    "./islands/overflow-modal.tsx": $overflow_modal,
    "./islands/suggested-searchbar.tsx": $suggested_searchbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
